### ISSUE TITLE
请教一个兼容性问题。

### ISSUE THREAD

**Issue by l42111996** [jannson/reedsolomon-c#3]
在服务器端 我用的 https://github.com/Backblaze/JavaReedSolomon   
客户端准备用这个库，不知道两个是否完全兼容？
我在java端写了个测试程序然后跟simple-encoder的输出做对比，发现得到的结果完全不同

**Comment by l42111996** [comment]
./a.out fec_test -d 2 -p 1 -o ./ -f 1.txt 
java的原数据
117-112-8712433-937-104-116120-3
生成的parity数据
-43-128-29116-1244

**Comment by jannson** [comment]
https://github.com/klauspost/reedsolomon

跟这个 golang 版本兼容。这个 java 版本我并不知道。你找找哪个 java 版本跟这个 golang 库兼容就行。
